# https://github.com/josh-tf/cbvpos  - Josh Bowden 2019-04-01
# Docker-Compose file - using ver 2 for compatibility
# download and run php, mysql and phpmyadmin containers
# downloads node, php modules on build.

version: '2'
services:

    cbv-dev-pos:
        container_name: cbv-dev-pos
        environment:
            - PHP_TIMEZONE=Australia/Melbourne
            - MYSQL_DB_NAME=cbvpos
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_HOST_NAME=cbv-dev-db
        image: joshtf/cbv-php
        links:
                - cbv-dev-db
        ports:
                - "80:80"
        restart: always
        volumes:
                - uploads:/app/public/uploads
                - ./app/:/app

    cbv-dev-db:
        container_name: cbv-dev-db
        environment:
            - MYSQL_USER=admin
            - MYSQL_DATABASE=cbvpos
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_ROOT_PASSWORD=pointofsale
        image: mysql:5.7
        ports:
                - "3306:3306"
        restart: always
        volumes:
                - ./app/database/cbvpos_import.sql:/docker-entrypoint-initdb.d/dump.sql

    cbv-dev-pma:
        container_name: cbv-dev-pma
        environment:
                - PMA_HOST=cbv-dev-db
        image: phpmyadmin/phpmyadmin
        links:
                - cbv-dev-db
        ports:
                - "8080:80"
        restart: always

# Build containers
#   - build composer installs codeigniter
#   - build-php installs php modules
#   - build-nodejs installs node and bower modules

    cbvposdev-build-composer:
        container_name: cbvposdev-build-composer
        image: composer/composer
        command: "install"
        volumes:
                - ./app/:/app

    cbvposdev-build-php:
        container_name: cbvposdev-build-php
        image: lucor/php7-cli
        command: "php install.php translations develop"
        volumes:
                - ./deploy/scripts/:/app

    cbvposdev-build-nodejs:
        container_name: cbvposdev-build-nodejs
        image: digitallyseamless/nodejs-bower-grunt
        command: bash -c "cd /app && npm install && bower install"
        volumes:
                - ./app/:/app

volumes:
    uploads:
        driver: local